services:
  backend:
    image: tracker-java:latest
    ports:
      - "8080:8080"
  db:
    image: "postgres:17-alpine"
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=postgres
      - POSTGRES_DB=/run/secrets/db_password
    secrets:
      - db_password
secrets:
  db_password:
    file: db_password.txt
