services:
  backend:
    image: tracker-java:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL= jdbc:postgresql://db:5432/postgres
  db:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data

    environment:
      - POSTGRES_PASSWORD= /run/secrets/db_password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    secrets:
      - db_password
secrets:
  db_password:
    file: ./db_password.txt
